version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"

  server:
    build: ./server
    volumes:
      - ./server/:/go/src/hello-grpc-web/server
    ports:
      - "9090:9090"
    container_name: "server"

  client:
    build: ./client
    volumes:
      - ./client/:/client
    ports:
      - "3000:3000"
